In [11]:
import pandas as pd
dataset = pd.read_csv("./pre-processed.csv")

In [12]:
dataset.head()

   index label                                  preprocessed_news
0      0  fake  katia abreu diz vai colocar expulsao moldura n...
1      1  fake  ray peita bolsonaro conservador fake entrevist...
2      2  fake  reinaldo azevedo desmascarado policia federal ...
3      3  fake  relatorio assustador bndes mostra dinheiro pub...
4      4  fake  radialista americano fala sobre pt vendem ilus...

In [13]:
dataset["label"].unique()

<ArrowStringArray>
['fake', 'true']
Length: 2, dtype: str

In [14]:
dic_correcao = {
    'fake': 0,
    'true': 1
}
dataset["Classe"] = dataset["label"].map(dic_correcao)
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 7200 entries, 0 to 7199
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   index              7200 non-null   int64
 1   label              7200 non-null   str
 2   preprocessed_news  7200 non-null   str
 3   Classe             7200 non-null   int64
dtypes: int64(2), str(2)
memory usage: 19.7 MB

In [15]:
dataset.to_csv("pre-processed_tratada.csv", index=False)

# Configurando variáveis de treinamento

In [ ]:
from sklearn.model_selection import train_test_split # Para dividir a "prova"

In [12]:
# Definir quem são as perguntas (X) e quem é a resposta (y)
dataset_shuffled = dataset.sample(frac=1).reset_index(drop=True)

x = dataset_shuffled["preprocessed_news"]
y = dataset_shuffled["Classificação"]

# Dividir a "prova" em 80% para treino e 20% para teste
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

print(f"Tamanho do Treino (Estudo): {x_train.shape[0]} noticias")
print(f"Tamanho do Teste (Prova): {x_test.shape[0]} noticias")

Tamanho do Treino (Estudo): 5760 noticias
Tamanho do Teste (Prova): 1440 noticias

In [14]:
y_train.head()

2034    0
3250    1
3366    0
1423    1
122     0
Name: Classificação, dtype: int64

In [15]:
dataset_shuffled.head()

,index,label,preprocessed_news,Classificação
0,571,fake,novo depoimento marcelo odebrecht destroi pt d...,0
1,4692,true,execucao irmaos negros es gera pedidos justica...,1
2,2394,fake,evitar ser arrastado depoimento defesa lula en...,0
3,515,fake,dialogo ministro justica corrupto governo chei...,0
4,4727,true,alvo mandado conducao coercitiva operacao janu...,1